---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: http-echo
        image: 097614841487.dkr.ecr.eu-west-2.amazonaws.com/http-echo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
