apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: http-echo
images:
- name: 097614841487.dkr.ecr.eu-west-2.amazonaws.com/http-echo
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
