apiVersion: v1
kind: Namespace
metadata:
  name: http-echo

---
apiVersion: v1
kind: Service
metadata:
  namespace: http-echo
  name: echo
  labels:
    app: echo
spec:
  type: LoadBalancer
  selector:
    app: echo
  ports:
  - name: http
    port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: http-echo
  name: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: http-echo
        image: 097614841487.dkr.ecr.eu-west-2.amazonaws.com/http-echo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
